print ('Importing')
import matlab.engine
print ('Starting Engine')
eng = matlab.engine.start_matlab()
print ('Finding Session')
name = matlab.engine.find_matlab()
names = ' ,'.join(name) 
print('Session Available: ' + names)
print ('connecting')
eng = matlab.engine.connect_matlab(name[0])
print ('connected')
eng.cd(r'C:\Users\hp\Dropbox\Projects\Pulse Tattoo', nargout=0)
your_name = input('Enter your name: ')
eng.u(your_name , nargout=0)